services:
  ssp:
    build: .
    volumes:
      - ./data:/data
    environment:
      - SSP_DOMAIN=${SSP_DOMAIN}
      - SSP_USERNAME=${SSP_USERNAME}
      - SSP_PASSWORD=${SSP_PASSWORD}


  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./data:/data
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.http.endpoint=http://ssp:8080/plugins/traefik/api_provider?id=api"
      - "--providers.http.pollInterval=60s"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
#      - "--certificatesresolvers.myresolver.acme.httpchallenge.caserver=xxx"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
